// Stable branded ids (AD-12, spine Consistency Conventions: Ids). Ids and the Project seed are
// generated by the shell (src/ui/ids.ts, nanoid) and passed into the core, so `apply` and redo
// stay deterministic (AD-2). The core never draws random ids itself.

import { z } from 'zod'

/** A default nanoid: 21 characters of the URL-safe alphabet. */
const ID_PATTERN = /^[A-Za-z0-9_-]{21}$/
const ID_LENGTH = 21

export const projectIdSchema = z.string().regex(ID_PATTERN).brand<'ProjectId'>()
export const projectSeedSchema = z.string().regex(ID_PATTERN).brand<'ProjectSeed'>()
export const stepIdSchema = z.string().regex(ID_PATTERN).brand<'StepId'>()
export const layerIdSchema = z.string().regex(ID_PATTERN).brand<'LayerId'>()

export type ProjectId = z.infer<typeof projectIdSchema>
/** The Project's PRNG seed (AD-2): generated at creation, kept by duplicate and Project File round-trips. */
export type ProjectSeed = z.infer<typeof projectSeedSchema>
export type StepId = z.infer<typeof stepIdSchema>
export type LayerId = z.infer<typeof layerIdSchema>

/** Produces a fresh id string. The shell passes nanoid; tests use `createDeterministicIdSource`. */
export type IdSource = () => string

/**
 * A counter-based id source for tests: the same call sequence always yields the same ids,
 * each a valid 21-character id (`<prefix>000…0001`).
 */
export function createDeterministicIdSource(prefix = 'id'): IdSource {
  if (!/^[A-Za-z_-]{1,10}$/.test(prefix)) throw new Error(`Invalid id prefix: ${prefix}`)
  let counter = 0
  return () => {
    counter += 1
    return `${prefix}${String(counter).padStart(ID_LENGTH - prefix.length, '0')}`
  }
}

export const toProjectId = (value: string): ProjectId => projectIdSchema.parse(value)
export const toProjectSeed = (value: string): ProjectSeed => projectSeedSchema.parse(value)
export const toStepId = (value: string): StepId => stepIdSchema.parse(value)
export const toLayerId = (value: string): LayerId => layerIdSchema.parse(value)
